<?php
    require '/usr/share/php/libphp-phpmailer/class.phpmailer.php';
    require '/usr/share/php/libphp-phpmailer/class.smtp.php';
    require 'spreadsheet/vendor/autoload.php';
    $file ='test.ods';
    $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($file);
    $xls_data = $spreadsheet->getActiveSheet()->toArray(null, true, true, true);
    $numberRow = count($xls_data);
    for ($i=1; $i<=$numberRow; $i++) {
        $mail = new PHPMailer;
        $mail->setFrom('sender_email');
        $mail->addAddress($xls_data[$i]['B']); //receiver_email from spreadsheet cell
        $mail->Subject = 'SALA-Teacher Application Credential';
        $mail->Body = '
            <div>Dear Lecturer, ' . $xls_data[$i]['A'] . '<div>
            <br/>
            <div>Here is your credential for accessing teacher portal.</div>
            <div>Email: <strong>' . $xls_data[$i]['B'] . '</strong></div>
            <div>Password: <strong>' . $xls_data[$i]['C'] . '</strong></div>
            <br/>
            <div>For any additional questions or concerns please email to <a href = "mailto: support@systemexpets.asia">support@systemexpets.asia</a> or call us at <strong>012240042 / 015 860 304.</strong></div>
            <br/>
            <div>Best regards,</div>
            <div>Channimol</div>
            <div>Dev, System Experts</div>
            <div>www.systemexperts.asia</div>
        ';
        $mail->isHTML(true);
        // $mail->AltBody = "This message is generated by plain text !";
        $mail->IsSMTP();
        $mail->SMTPSecure = 'ssl';
        $mail->Host = 'ssl://smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Port = 465;

        //Set your existing gmail address as user name
        $mail->Username = 'sender_email';

        //Set the password of your gmail address here
        $mail->Password = 'sender_password';
        if(!$mail->send()) {
            echo 'Email is not sent to ' . $xls_data[$i]['B'];
            echo 'Email error: ' . $mail->ErrorInfo;
        } else {
            echo 'Email has been sent to ' . $xls_data[$i]['B'];
        }
    }
?>
